---
# TID-Playbook resetnodes
# Este playbook reseteará los nodos a su estado inicial sin git ni LiME

- name: Restaurar nodos Ubuntu
  hosts: all
  become: yes
  
  tasks:
  
    - name: Desinstalar git
      apt:
        pkg: git
        state: absent

    - name: Desinstalar dependencias
      apt:
        pkg:
          - make
          - build-essential
          - "linux-headers-{{ansible_facts.kernel}}"
        state: absent
        autoremove: yes

    - name: Borrar carpeta LiME
      file:
        path: "{{homedirectory}}/LiME"
        state: absent
