# PlaybookMemoryLinux
# Este playbook realiza una adquisición de memoria de un nodo Linux utilizando LiME
# Si el nodo no está preparado para realizar la adquisición realiza las tareas necesarias para prepararlo
# La adquisición se realiza se almacena en formato raw en un fichero .dd en la máquina controladora

- name: Adquirir memoria en Ubuntu
  hosts: all
  tasks:
  - name: Comprobar LiME
    import_role:
        name: checklime

  - name: Instalar LiME
    include_role:
      name: installlime
    when: checklimeresult=="0"

  - name: Etiquetar evidencia
    import_role:
      name: labelevidence
    vars:
      evidencetype: "{{memorydumpname}}"
      evidenceextension: "{{memorydumpextension}}"

  - name: Adquirir memoria
    import_role:
      name: dumpmemorylinux
    vars:
      memorydumplabel: "{{evidencelabel}}"
