---
# tasks file for checklime
# checklime comprobará la existencia de LiME en el nodo.
#Si 
#  existe el directorio LiME en home 
#entonces 0

- name: Buscar LiME
  find:
    paths: "{{homedirectory}}"
    patterns: "LiME"
    file_type: directory
  register: resultado
  
- name: guardar resultado checklime
  set_fact:
    checklimeresult: "{{resultado.matched}}"

