---
# El role labelevidence etiquetar치 una evidencia:
#  Nombre del tipo de evidencia
#  Fecha y hora
#  Usuario
#  Nodo

- name: A침adir hora
  set_fact:
    evidencelabel: "{{evidencetype}}-{{ansible_facts.date_time.iso8601_basic_short}}{{evidenceextension}}"
    
- name: A침adir usuario
  set_fact:
    userpath: "{{storagepath}}/{{ansible_facts.user_id}}"
    
- name: A침adir nodo
  set_fact:
    completepath: "{{userpath}}/{{inventory_hostname}}"
